import { IOrders, IProduct, IProductsInOrders, IUser } from './interface';

export const randomUsers: IUser[] = [
    { id: 1, first_name: 'Milena', last_name: 'Petrovic', password: 'milena' },
    { id: 2, first_name: 'Nikola', last_name: 'Jovanovic', password: 'nikola' },
    {
        id: 3,
        first_name: 'Katarina',
        last_name: 'Popovic',
        password: 'katarina',
    },
    { id: 4, first_name: 'Jelena', last_name: 'Simic', password: 'jelena' },
    { id: 5, first_name: 'Stefan', last_name: 'Kovacevic', password: 'stefan' },
    { id: 6, first_name: 'Dusan', last_name: 'Vukovic', password: 'dusan' },
    {
        id: 7,
        first_name: 'Anastasija',
        last_name: 'Milinkovic',
        password: 'anastasija',
    },
    { id: 8, first_name: 'Petar', last_name: 'Stojanovic', password: 'petar' },
    {
        id: 9,
        first_name: 'Aleksandra',
        last_name: 'Lazic',
        password: 'aleksandra',
    },
    { id: 10, first_name: 'Tijana', last_name: 'Vasic', password: 'tijana' },
    { id: 11, first_name: 'Mina', last_name: 'Mitic', password: 'mina' },
    { id: 12, first_name: 'Luka', last_name: 'Ristic', password: 'luka' },
    { id: 13, first_name: 'Jovana', last_name: 'Pavlovic', password: 'jovana' },
    { id: 14, first_name: 'Nenad', last_name: 'Petrovic', password: 'nenad' },
    {
        id: 15,
        first_name: 'Milica',
        last_name: 'Djordjevic',
        password: 'milica',
    },
    {
        id: 16,
        first_name: 'Andrija',
        last_name: 'Nikolic',
        password: 'andrija',
    },
    { id: 17, first_name: 'Sara', last_name: 'Lukic', password: 'sara' },
    { id: 18, first_name: 'Ognjen', last_name: 'Markovic', password: 'ognjen' },
    { id: 19, first_name: 'Dunja', last_name: 'Tomic', password: 'dunja' },
    {
        id: 20,
        first_name: 'Aleksa',
        last_name: 'Stankovic',
        password: 'aleksa',
    },
    {
        id: 21,
        first_name: 'Teodora',
        last_name: 'Milovanovic',
        password: 'teodora',
    },
    { id: 22, first_name: 'Filip', last_name: 'Simovic', password: 'filip' },
    { id: 23, first_name: 'Milan', last_name: 'Rakic', password: 'milan' },
    { id: 24, first_name: 'Novak', last_name: 'Gavrilovic', password: 'novak' },
    { id: 25, first_name: 'Milos', last_name: 'Nikolic', password: 'milos' },
    { id: 26, first_name: 'Ivana', last_name: 'Djokovic', password: 'ivana' },
    {
        id: 27,
        first_name: 'Strahinja',
        last_name: 'Jokic',
        password: 'strahinja',
    },
    { id: 28, first_name: 'Milan', last_name: 'Maksimovic', password: 'milan' },
    { id: 29, first_name: 'Hana', last_name: 'Peric', password: 'hana' },
    {
        id: 30,
        first_name: 'Mihajlo',
        last_name: 'Zivkovic',
        password: 'mihajlo',
    },
];

export const radnomProducts: IProduct[] = [
    { id: 1, name: 'Laptop', price: 799.99, category: 'electronics' },
    { id: 2, name: 'T-shirt', price: 14.99, category: 'clothing' },
    { id: 3, name: 'Microwave', price: 99.99, category: 'appliances' },
    { id: 4, name: 'Sofa', price: 499.99, category: 'furniture' },
    { id: 5, name: 'Coffee', price: 6.99, category: 'rest' },
    { id: 6, name: 'Smartphone', price: 599.99, category: 'electronics' },
    { id: 7, name: 'Jeans', price: 29.99, category: 'clothing' },
    { id: 8, name: 'Blender', price: 39.99, category: 'appliances' },
    { id: 9, name: 'Dining Table', price: 299.99, category: 'furniture' },
    { id: 10, name: 'Pizza', price: 11.99, category: 'rest' },
    { id: 11, name: 'TV', price: 499.99, category: 'electronics' },
    { id: 12, name: 'Dress', price: 24.99, category: 'clothing' },
    { id: 13, name: 'Washing Machine', price: 299.99, category: 'appliances' },
    { id: 14, name: 'Bed', price: 399.99, category: 'furniture' },
    { id: 15, name: 'Burger', price: 7.99, category: 'rest' },
    { id: 16, name: 'Headphones', price: 99.99, category: 'electronics' },
    { id: 17, name: 'Shoes', price: 39.99, category: 'clothing' },
    { id: 18, name: 'Toaster', price: 19.99, category: 'appliances' },
    { id: 19, name: 'Bookshelf', price: 89.99, category: 'furniture' },
    { id: 20, name: 'Salad', price: 5.99, category: 'rest' },
    { id: 21, name: 'Tablet', price: 199.99, category: 'electronics' },
    { id: 22, name: 'Jacket', price: 49.99, category: 'clothing' },
    { id: 23, name: 'Refrigerator', price: 599.99, category: 'appliances' },
    { id: 24, name: 'Desk', price: 149.99, category: 'furniture' },
    { id: 25, name: 'Ice Cream', price: 4.99, category: 'rest' },
    { id: 26, name: 'Camera', price: 349.99, category: 'electronics' },
    { id: 27, name: 'Socks', price: 9.99, category: 'clothing' },
    { id: 28, name: 'Coffee Maker', price: 29.99, category: 'appliances' },
    { id: 29, name: 'Nightstand', price: 79.99, category: 'furniture' },
    { id: 30, name: 'Soup', price: 3.99, category: 'rest' },
    { id: 31, name: 'Keyboard', price: 49.99, category: 'electronics' },
    { id: 32, name: 'Hat', price: 12.99, category: 'clothing' },
    { id: 33, name: 'Vacuum Cleaner', price: 79.99, category: 'appliances' },
    { id: 34, name: 'Couch', price: 399.99, category: 'furniture' },
    { id: 35, name: 'Pasta', price: 4.99, category: 'rest' },
];

export const randomOrders: IOrders[] = [
    { id: 1, user_id: 1, status: 'active' },
    { id: 2, user_id: 2, status: 'active' },
    { id: 3, user_id: 3, status: 'active' },
    { id: 4, user_id: 1, status: 'complete' },
    { id: 5, user_id: 4, status: 'complete' },
    { id: 6, user_id: 1, status: 'active' },
    { id: 7, user_id: 2, status: 'complete' },
    { id: 8, user_id: 3, status: 'complete' },
    { id: 9, user_id: 4, status: 'active' },
    { id: 10, user_id: 5, status: 'active' },
    { id: 11, user_id: 6, status: 'active' },
    { id: 12, user_id: 7, status: 'complete' },
    { id: 13, user_id: 11, status: 'active' },
    { id: 14, user_id: 12, status: 'active' },
    { id: 15, user_id: 13, status: 'complete' },
    { id: 16, user_id: 14, status: 'active' },
    { id: 17, user_id: 14, status: 'complete' },
    { id: 18, user_id: 14, status: 'active' },
    { id: 19, user_id: 15, status: 'active' },
    { id: 20, user_id: 16, status: 'complete' },
    { id: 21, user_id: 16, status: 'active' },
    { id: 22, user_id: 17, status: 'active' },
    { id: 23, user_id: 20, status: 'complete' },
    { id: 24, user_id: 21, status: 'active' },
    { id: 25, user_id: 22, status: 'active' },
    { id: 26, user_id: 23, status: 'complete' },
    { id: 27, user_id: 24, status: 'active' },
    { id: 28, user_id: 24, status: 'complete' },
    { id: 29, user_id: 24, status: 'active' },
    { id: 30, user_id: 25, status: 'complete' },
    { id: 31, user_id: 26, status: 'complete' },
    { id: 32, user_id: 27, status: 'active' },
    { id: 33, user_id: 28, status: 'active' },
];

export const randomProductInOrder: IProductsInOrders[] = [
    { id: 1, quantity: 3, product_id: 1, order_id: 1 },
    { id: 2, quantity: 3, product_id: 1, order_id: 2 },
    { id: 3, quantity: 3, product_id: 2, order_id: 2 },
    { id: 4, quantity: 3, product_id: 2, order_id: 1 },
    { id: 5, quantity: 4, product_id: 3, order_id: 1 },
    { id: 6, quantity: 4, product_id: 5, order_id: 1 },
    { id: 7, quantity: 4, product_id: 7, order_id: 1 },
    { id: 8, quantity: 4, product_id: 8, order_id: 1 },
    { id: 9, quantity: 4, product_id: 8, order_id: 2 },
    { id: 10, quantity: 4, product_id: 8, order_id: 3 },
    { id: 11, quantity: 4, product_id: 8, order_id: 5 },
    { id: 12, quantity: 4, product_id: 5, order_id: 5 },
    { id: 13, quantity: 4, product_id: 5, order_id: 4 },
    { id: 14, quantity: 4, product_id: 5, order_id: 3 },
    { id: 15, quantity: 4, product_id: 5, order_id: 2 },
    { id: 16, quantity: 4, product_id: 12, order_id: 4 },
    { id: 17, quantity: 4, product_id: 22, order_id: 4 },
    { id: 18, quantity: 1, product_id: 32, order_id: 4 },
    { id: 19, quantity: 2, product_id: 6, order_id: 1 },
    { id: 20, quantity: 1, product_id: 6, order_id: 2 },
    { id: 21, quantity: 1, product_id: 6, order_id: 3 },
    { id: 22, quantity: 3, product_id: 6, order_id: 5 },
    { id: 23, quantity: 4, product_id: 9, order_id: 1 },
    { id: 24, quantity: 1, product_id: 10, order_id: 1 },
    { id: 25, quantity: 1, product_id: 11, order_id: 1 },
    { id: 26, quantity: 1, product_id: 13, order_id: 1 },
    { id: 27, quantity: 1, product_id: 16, order_id: 1 },
    { id: 28, quantity: 1, product_id: 18, order_id: 1 },
    { id: 29, quantity: 2, product_id: 18, order_id: 3 },
    { id: 30, quantity: 2, product_id: 28, order_id: 3 },
    { id: 31, quantity: 2, product_id: 29, order_id: 3 },
    { id: 32, quantity: 2, product_id: 33, order_id: 3 },
    { id: 33, quantity: 2, product_id: 35, order_id: 3 },
    { id: 34, quantity: 3, product_id: 4, order_id: 3 },
    { id: 35, quantity: 3, product_id: 15, order_id: 3 },
    { id: 36, quantity: 2, product_id: 15, order_id: 4 },
    { id: 37, quantity: 2, product_id: 25, order_id: 4 },
];
