import { IProduct, IUser } from './interface';

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export const randomUsers: IUser[] = [
    { first_name: 'Milena', last_name: 'Petrovic', password: 'milena' },
    { first_name: 'Nikola', last_name: 'Jovanovic', password: 'nikola' },
    { first_name: 'Katarina', last_name: 'Popovic', password: 'katarina' },
    { first_name: 'Jelena', last_name: 'Simic', password: 'jelena' },
    { first_name: 'Stefan', last_name: 'Kovacevic', password: 'stefan' },
    { first_name: 'Dusan', last_name: 'Vukovic', password: 'dusan' },
    {
        first_name: 'Anastasija',
        last_name: 'Milinkovic',
        password: 'anastasija',
    },
    { first_name: 'Petar', last_name: 'Stojanovic', password: 'petar' },
    { first_name: 'Aleksandra', last_name: 'Lazic', password: 'aleksandra' },
    { first_name: 'Tijana', last_name: 'Vasic', password: 'tijana' },
    { first_name: 'Mina', last_name: 'Mitic', password: 'mina' },
    { first_name: 'Luka', last_name: 'Ristic', password: 'luka' },
    { first_name: 'Jovana', last_name: 'Pavlovic', password: 'jovana' },
    { first_name: 'Nenad', last_name: 'Petrovic', password: 'nenad' },
    { first_name: 'Milica', last_name: 'Djordjevic', password: 'milica' },
    { first_name: 'Andrija', last_name: 'Nikolic', password: 'andrija' },
    { first_name: 'Sara', last_name: 'Lukic', password: 'sara' },
    { first_name: 'Ognjen', last_name: 'Markovic', password: 'ognjen' },
    { first_name: 'Dunja', last_name: 'Tomic', password: 'dunja' },
    { first_name: 'Aleksa', last_name: 'Stankovic', password: 'aleksa' },
    { first_name: 'Teodora', last_name: 'Milovanovic', password: 'teodora' },
    { first_name: 'Filip', last_name: 'Simovic', password: 'filip' },
    { first_name: 'Milan', last_name: 'Rakic', password: 'milan' },
    { first_name: 'Novak', last_name: 'Gavrilovic', password: 'novak' },
    { first_name: 'Milos', last_name: 'Nikolic', password: 'milos' },
    { first_name: 'Ivana', last_name: 'Djokovic', password: 'ivana' },
    { first_name: 'Strahinja', last_name: 'Jokic', password: 'strahinja' },
    { first_name: 'Milan', last_name: 'Maksimovic', password: 'milan' },
    { first_name: 'Hana', last_name: 'Peric', password: 'hana' },
    { first_name: 'Mihajlo', last_name: 'Zivkovic', password: 'mihajlo' },
];

export const radnomProducts: IProduct[] = [
    { name: 'Laptop', price: 799.99, category: 'electronics' },
    { name: 'T-shirt', price: 14.99, category: 'clothing' },
    { name: 'Microwave', price: 99.99, category: 'appliances' },
    { name: 'Sofa', price: 499.99, category: 'furniture' },
    { name: 'Coffee', price: 6.99, category: 'rest' },
    { name: 'Smartphone', price: 599.99, category: 'electronics' },
    { name: 'Jeans', price: 29.99, category: 'clothing' },
    { name: 'Blender', price: 39.99, category: 'appliances' },
    { name: 'Dining Table', price: 299.99, category: 'furniture' },
    { name: 'Pizza', price: 11.99, category: 'rest' },
    { name: 'TV', price: 499.99, category: 'electronics' },
    { name: 'Dress', price: 24.99, category: 'clothing' },
    { name: 'Washing Machine', price: 299.99, category: 'appliances' },
    { name: 'Bed', price: 399.99, category: 'furniture' },
    { name: 'Burger', price: 7.99, category: 'rest' },
    { name: 'Headphones', price: 99.99, category: 'electronics' },
    { name: 'Shoes', price: 39.99, category: 'clothing' },
    { name: 'Toaster', price: 19.99, category: 'appliances' },
    { name: 'Bookshelf', price: 89.99, category: 'furniture' },
    { name: 'Salad', price: 5.99, category: 'rest' },
    { name: 'Tablet', price: 199.99, category: 'electronics' },
    { name: 'Jacket', price: 49.99, category: 'clothing' },
    { name: 'Refrigerator', price: 599.99, category: 'appliances' },
    { name: 'Desk', price: 149.99, category: 'furniture' },
    { name: 'Ice Cream', price: 4.99, category: 'rest' },
    { name: 'Camera', price: 349.99, category: 'electronics' },
    { name: 'Socks', price: 9.99, category: 'clothing' },
    { name: 'Coffee Maker', price: 29.99, category: 'appliances' },
    { name: 'Nightstand', price: 79.99, category: 'furniture' },
    { name: 'Soup', price: 3.99, category: 'rest' },
    { name: 'Keyboard', price: 49.99, category: 'electronics' },
    { name: 'Hat', price: 12.99, category: 'clothing' },
    { name: 'Vacuum Cleaner', price: 79.99, category: 'appliances' },
    { name: 'Couch', price: 399.99, category: 'furniture' },
    { name: 'Pasta', price: 4.99, category: 'rest' },
];
